name: Build and Deploy

on:
    push:
        branches:
            - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v6
            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages # The branch the action should deploy to.
                  folder: dist # The folder the action should deploy.
                  single-commit: true
